openapi: 3.0.0
servers:
  - url: 'https://tkb2.ncats.io/'
info:
  title: Translator Knowledge Beacon API
  version: 2.0.0
  contact:
    url: 'http://starinformatics.com'
    email: richard@starinformatics.com
    responsibleDeveloper: Richard Bruskiewich
    responsibleOrganization: STAR Informatics/Delphinai Corporation
  description: >
    This is Release 2.0 of the Translator Knowledge Beacon Aggregator web
    service application programming interface (API). Release 2.0 is a major
    release departure from 1.0.* in that it is based on Semantic Automated
    Discovery and Integration (SADI) which is an RDF OWL REST web service
    protocol. Briefly, each end point here has a "GET" which returns a SADI
    service description (as RDF) and a "POST" which processes a service based on
    service description input parameters, returning an annotated version of the
    document.
  license:
    name: MIT License
    url: 'http://opensource.org/licenses/MIT'
tags:
  - name: summary
    description: Summary statistics about the knowledge source
  - name: concepts
    description: Queries for concepts
  - name: predicates
    description: Queries for predicates
  - name: exactmatches
    description: >-
      Queries for exactly matching concepts *sensa*-SKOS;
      http://www.w3.org/2004/02/skos/core#exactMatch
  - name: statements
    description: Queries for concept-relationship statements
  - name: evidence
    description: Queries for references cited as evidence for statements
paths:
  /types:
    get:
      description: >
        Get a list of types and # of instances in the knowledge source, and a
        link to the API call for the list of equivalent terminology
      tags:
        - summary
      operationId: linkedTypes
      responses:
        '200':
          description: |
            Successful RDF response with types and frequency returned
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Summary
                  type: object
                  properties:
                    id:
                      type: string
                      description: |
                        the type 
                    idmap:
                      type: string
                      description: The URL to execute the exactmatches API call on the id
                    frequency:
                      type: integer
                      description: |
                        the number of instances of the specified type
              examples:
                response:
                  value:
                    - id: CHEM
                      frequency: 12355
                      idmap: 'http://myservice.net/api/v1/exactmatches/CHEM'
                    - id: ANAT
                      frequency: 1234
                      idmap: 'http://myservice.net/api/v1/exactmatches/ANAT'
  '/concepts/{conceptId}':
    get:
      description: >
        Retrieves details for a specified concepts in the system, as specified
        by a (url-encoded) CURIE identifier of a concept known the given
        knowledge source.
      tags:
        - concepts
      parameters:
        - name: conceptId
          in: path
          description: (url-encoded) CURIE identifier of concept of interest
          required: true
          schema:
            type: string
      operationId: getConceptDetails
      responses:
        '200':
          description: |
            Successful response with concept details returned
          content:
            application/json:
              schema:
                type: array
                items:
                  title: ConceptWithDetails
                  type: object
                  properties:
                    id:
                      type: string
                      description: >
                        local object identifier for the concept in the specified
                        knowledge source database
                    name:
                      type: string
                      description: |
                        canonical human readable name of the concept
                    semanticGroup:
                      type: string
                      description: |
                        concept semantic type
                    synonyms:
                      type: array
                      description: |
                        list of synonyms for concept
                      items:
                        type: string
                    definition:
                      type: string
                      description: |
                        concept definition
                    details:
                      type: array
                      items:
                        title: ConceptDetail
                        type: object
                        properties:
                          tag:
                            type: string
                            description: |
                              property name
                          value:
                            type: string
                            description: |
                              property value
              examples:
                response:
                  value:
                    - id: 'wd:Q14883734'
                      name: WRN
                      semanticGroup: GENE
                      synonyms: []
                      definition: Werner Syndrome Gene
                      details: []
  /concepts:
    get:
      description: |
        Retrieves a (paged) list of concepts in the system
      tags:
        - concepts
      parameters:
        - name: keywords
          in: query
          description: >-
            a (urlencoded) space delimited set of keywords or substrings against
            which to match concept names and synonyms
          required: true
          schema:
            type: string
        - name: semanticGroups
          in: query
          description: >
            a (url-encoded) space-delimited set of semantic groups (specified as
            codes CHEM, GENE, ANAT, etc.) to which to constrain concepts matched
            by the main keyword search (see [Semantic
            Groups](https://metamap.nlm.nih.gov/Docs/SemGroups_2013.txt) for the
            full list of codes)
          required: false
          schema:
            type: string
        - name: pageNumber
          in: query
          description: |
            (1-based) number of the page to be returned in a paged set of query
            results
          required: false
          schema:
            type: integer
        - name: pageSize
          in: query
          description: |
            number of concepts per page to be returned in a paged set of query
            results
          required: false
          schema:
            type: integer
      operationId: getConcepts
      responses:
        '200':
          description: |
            Successful response with concept list returned
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Concept
                  type: object
                  properties:
                    id:
                      type: string
                      description: >
                        local object identifier for the concept in the specified
                        knowledge source database
                    name:
                      type: string
                      description: |
                        canonical human readable name of the concept
                    semanticGroup:
                      type: string
                      description: |
                        concept semantic type
                    synonyms:
                      type: array
                      description: |
                        list of synonyms for concept
                      items:
                        type: string
                    definition:
                      type: string
                      description: |
                        concept definition
              examples:
                response:
                  value:
                    - id: 'wd:Q6591532'
                      name: 'WRN protein, human'
                      semanticGroup: CHEM
                      synonyms:
                        - RecQ3
                        - Werner Syndrome ATP-Dependent Helicase
                        - 'RECQL2 protein, human'
                        - EC 3.1.-.-
                        - 'WRN protein, human'
                        - WRN
                        - Exonuclease WRN
                        - Werner Syndrome Protein
                        - RecQ Protein-Like 2
                        - EC 3.6.4.12
                        - 'RECQ3 protein, human'
                        - 'Werner syndrome helicase, human'
                        - WRN Protein
                        - 'DNA Helicase, RecQ-Like Type 3'
                      definition: >-
                        Werner syndrome ATP-dependent helicase (1432 aa, ~162
                        kDa) is encoded by the human WRN gene. This protein
                        plays a role in both magnesium and ATP-dependent
                        DNA-helicase activity and 3\'->5\' exonuclease activity
                        towards double-stranded DNA with a 5\'-overhang.
                    - id: 'wd:Q18042562'
                      name: WRNIP1
                      semanticGroup: GENE
                      synonyms:
                        - WHIP
                        - Werner helicase interacting protein 1
                        - WRNIP1
                        - bA420G6.2
                      definition: human gene
                    - id: 'wd:Q14883734'
                      name: WRN
                      semanticGroup: GENE
                      synonyms:
                        - RECQ3
                        - RECQL3
                        - Werner syndrome RecQ like helicase
                        - RECQL2
                      definition: human gene
                    - id: 'wd:Q1154619'
                      name: Werner Syndrome
                      semanticGroup: DISO
                      synonyms:
                        - Werner Syndrome
                        - Pangeria
                        - 'Syndrome, Werner'
                        - 'Progeria, Adult'
                        - 'Werner Syndrome [Disease/Finding]'
                        - Werner syndrome (disorder)
                        - adult progeria
                        - Werner
                        - syndromes werner
                        - 'Syndrome, Werner\''s'
                        - WRN
                        - Werner\'s syndrome
                        - adults progeria
                        - Werner syndrome (adult progeria) (diagnosis)
                        - Werner syndrome (adult progeria)
                        - 'Syndrome, Werners'
                        - Adult premature aging syndrome
                        - syndromes werner\'s
                        - Werners Syndrome
                        - syndrome werner
                        - Progeria of the adult
                        - WS
                        - syndromes werners
                        - Adult premature ageing syndrome
                      definition: >-
                        autosomal recessive disorder that causes premature aging
                        in adults, characterized by sclerodermal skin changes,
                        cataracts, subcutaneous calcifications, muscular
                        atrophy, a tendency to diabetes mellitus, aged
                        appearance of the face, baldness, and a high incidence
                        of neoplastic disease.
  /predicates:
    get:
      description: >
        Get a list of predicates used in statements issued by the knowledge
        source
      tags:
        - predicates
      operationId: getPredicates
      responses:
        '200':
          description: >
            Successful response with predicates with CURIE and definitions
            indexed by beacons which support the relation
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Predicate
                  type: object
                  properties:
                    id:
                      type: string
                      description: |
                        CURIE-encoded identifier of predicate resource
                    name:
                      type: string
                      description: |
                        human readable name of predicate relation
                    definition:
                      type: string
                      description: >
                        human readable definition of predicate relation provided
                        by this beacon
              examples:
                response:
                  value:
                    - id: 'wd:P123'
                      name: interacts with
                      definition: influences in some manner
                    - id: 'wd:P456'
                      name: has phenotype
                      definition: exhibits biological morphology or behaviour
  '/exactmatches/{conceptId}':
    get:
      description: >
        Retrieves a list of qualified identifiers of "exact match" concepts,
        [sensa SKOS](http://www.w3.org/2004/02/skos/core#exactMatch) associated
        with a specified (url-encoded) CURIE (without brackets) concept object
        identifier,  typically, of a concept selected from the list of concepts
        originally returned by a /concepts API call on a given KS. 
      tags:
        - exactmatches
      parameters:
        - name: conceptId
          in: path
          description: (url-encoded) CURIE identifier of the concept to be matched
          required: true
          schema:
            type: string
      operationId: getExactMatchesToConcept
      responses:
        '200':
          description: >
            Successful response returns a set of
            [CURIE](https://www.w3.org/TR/curie/) identifiers to 3rd party
            concepts defined outside of the local KS, which are deemed semantic
            exact matches
            [*sensa*-SKOS](http://www.w3.org/2004/02/skos/core#exactMatch) to 
            the specified identified concept (maybe an empty set?)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                response:
                  value:
                    - 'wd:Q14883734'
                    - 'NCBIGene:7486'
  /exactmatches:
    get:
      description: >
        Given an input list of [CURIE](https://www.w3.org/TR/curie/) identifiers
        of known exactly matched concepts
        [*sensa*-SKOS](http://www.w3.org/2004/02/skos/core#exactMatch),
        retrieves the list of [CURIE](https://www.w3.org/TR/curie/) identifiers
        of of additional concepts that are deemed by the given knowledge source
        to be exact matches to one or more of the input concepts **plus**
        whichever identifiers from the input list which specifically matched
        these new additional concepts.  If an empty set is returned, the it can
        be assumed that the given knowledge source does not know of any new
        equivalent concepts matching the input set.
      tags:
        - exactmatches
      parameters:
        - name: c
          in: query
          description: >
            set of [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers of
            exactly matching concepts, to be used in a search for additional
            exactly matching concepts
            [*sensa*-SKOS](http://www.w3.org/2004/02/skos/core#exactMatch).
          required: true
          schema:
            type: array
            items:
              type: string
      operationId: getExactMatchesToConceptList
      responses:
        '200':
          description: >
            Successful response returns a set of
            [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers of
            concepts (with supporting evidence code and reference) matching at
            least one identifier in the input list of known exactly matched
            concepts
            [*sensa*-SKOS](http://www.w3.org/2004/02/skos/core#exactMatch). Each
            concept identifier is returned with  the full list of any additional
            associated [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers
            of exact match concepts known to the given Knowledge Source.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: >
                    [CURIE](https://www.w3.org/TR/curie/) identifier of an exact
                    matching concept not yet listed in the input set of exact
                    matching concepts.
              examples:
                response:
                  value:
                    - 'wd:Q14883734'
                    - 'NCBIGene:7486'
  /statements:
    get:
      description: >
        Given a list of [CURIE-encoded](https://www.w3.org/TR/curie/)
        identifiers of exactly matching concepts, OR the CUIR of a target 
        'subject' and/or 'object' concept, retrieves a paged list of
        concept-relations where either the subject or object concept matches at
        least one concept in the input list, or the given  'subject' and/or
        'object' concept.
      tags:
        - statements
      parameters:
        - name: c
          in: query
          description: >
            set of [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers of
            exactly matching concepts to be used in a search for associated
            concept-relation statements. From 1.0.15 onwards, the 'c' list 
            parameter is now NOT mandatory; however IF it is not given, then a
            specific subject and/or object parameter must be provided (see
            below)
          required: false
          schema:
            type: array
            items:
              type: string
        - name: subject
          in: query
          description: >
            a [CURIE-encoded](https://www.w3.org/TR/curie/) identifier of the
            concept to be used as the 'subject' target in the  search for
            associated concept - relationship statements.
          required: false
          schema:
            type: string
        - name: relations
          in: query
          description: >
            a (url-encoded, space-delimited) string of predicate relation
            identifiers with which to constrain the statement relations
            retrieved  for the given query seed concept. The predicate ids sent
            should  be as published by the beacon-aggregator by the /predicates
            API endpoint.
          required: false
          schema:
            type: string
        - name: object
          in: query
          description: >
            a [CURIE-encoded](https://www.w3.org/TR/curie/) identifier of the
            concept to be used as the 'object' target in the  search for
            associated concept - relationship statements.
          required: false
          schema:
            type: string
        - name: keywords
          in: query
          description: >
            a (url-encoded, space-delimited) string of keywords or substrings
            against which to match the subject, predicate or object names of the
            set of concept-relations matched by any of the input exact matching
            concepts
          required: false
          schema:
            type: string
        - name: semanticGroups
          in: query
          description: >
            a (url-encoded, space-delimited) string of semantic groups
            (specified as codes CHEM, GENE, ANAT, etc.) to which to constrain
            the subject or object concepts associated with the query seed
            concept (see [Semantic
            Groups](https://metamap.nlm.nih.gov/Docs/SemGroups_2013.txt) for the
            full list of codes)
          required: false
          schema:
            type: string
        - name: pageNumber
          in: query
          description: |
            (1-based) number of the page to be returned in a paged set of query
            results
          required: false
          schema:
            type: integer
        - name: pageSize
          in: query
          description: |
            number of concepts per page to be returned in a paged set of query
            results
          required: false
          schema:
            type: integer
      operationId: getStatements
      responses:
        '200':
          description: >
            Successful response returns a list of concept-relations where there
            is an exact match of an input concept identifier either to the
            subject or object concepts of the statement
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Statement
                  type: object
                  properties:
                    id:
                      type: string
                      description: >-
                        CURIE-encoded identifier for statement (can be used to
                        retrieve associated evidence)
                    subject:
                      title: StatementSubject
                      type: object
                      properties:
                        id:
                          type: string
                          description: |
                            CURIE-encoded identifier of concept
                        name:
                          type: string
                          description: human readable label of subject concept
                        semanticGroup:
                          type: string
                          description: >
                            a semantic group for the subject concept (specified
                            as a code CHEM, GENE, etc. - see [Semantic
                            Groups](https://metamap.nlm.nih.gov/Docs/SemGroups_2013.txt)
                            for the full list of codes)
                    predicate:
                      title: StatementPredicate
                      type: object
                      properties:
                        id:
                          type: string
                          description: |
                            CURIE-encoded identifier of predicate resource
                        name:
                          type: string
                          description: human readable label of concept
                    object:
                      title: StatementObject
                      type: object
                      properties:
                        id:
                          type: string
                          description: |
                            CURIE-encoded identifier of object concept
                        name:
                          type: string
                          description: human readable label of object concept
                        semanticGroup:
                          type: string
                          description: >
                            a semantic group for the object concept (specified
                            as a code CHEM, GENE, etc. - see [Semantic
                            Groups](https://metamap.nlm.nih.gov/Docs/SemGroups_2013.txt)
                            for the full list of codes)
              examples:
                response:
                  value:
                    - source: semmeddb
                      id: 'kb:12345'
                      subject:
                        id:
                          - 'wd:Q14912054'
                        name: KCNJ11
                        semanticGroup: GENE
                      predicate:
                        id:
                          - 'kbp:10'
                        name: Causes
                      object:
                        id:
                          - 'wd:Q2898645'
                        name: Neonatal diabetes mellitus
                        semanticGroup: DISO
  '/evidence/{statementId}':
    get:
      description: >
        Retrieves a (paged) list of annotations cited as evidence for a
        specified concept-relationship statement
      tags:
        - evidence
      parameters:
        - name: statementId
          in: path
          description: >
            (url-encoded) CURIE identifier of the concept-relationship statement
            ("assertion", "claim") for which associated evidence is sought
          required: true
          schema:
            type: string
        - name: keywords
          in: query
          description: >
            (url-encoded, space delimited) keyword filter to apply against the
            label field of the annotation
          required: false
          schema:
            type: string
        - name: pageNumber
          in: query
          description: |
            (1-based) number of the page to be returned in a paged set of query
            results
          required: false
          schema:
            type: integer
        - name: pageSize
          in: query
          description: >
            number of cited references per page to be returned in a paged set of
            query results
          required: false
          schema:
            type: integer
      operationId: getEvidence
      responses:
        '200':
          description: |
            successful call returns a list of annotation with metadata
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Annotation
                  type: object
                  properties:
                    id:
                      type: string
                      description: >
                        CURIE-encoded identifier to an associated external
                        resources (e.g. PMID of a pubmed citation)
                    label:
                      type: string
                      description: >
                        canonical human readable and searchable label of the
                        annotation (i.e. comment, matched sentence, etc.)
                    type:
                      type: string
                      description: >
                        Gene Ontology Evidence Code
                        (http://www.geneontology.org/page/guide-go-evidence-codes)
                    date:
                      type: string
                      description: >
                        publication date of annotation (generally of format
                        'yyyy-mm-dd')
                    provenance:
                      title: Provenance
                      type: object
                      properties:
                        authority:
                          type: string
                          description: >
                            Specific scientific authority asserting the
                            evidence. Maybe be a database name, software tool or
                            human scientific authority(?)
                        url:
                          type: string
                          description: |
                            URL to provenance authority details
                        metadata:
                          type: string
                          description: >
                            Optional comma delimited tag = value key pairs
                            qualifying the nature of the provenance, e.g.
                            database or software version, software input
                            parameters, etc.
              examples:
                response:
                  value:
                    - id:
                        - 'pmid:22781086'
                      label: >-
                        Neonatal diabetes mellitus and congenital diaphragmatic
                        hernia coincidence or concurrent etiology?
                      type: TAS
                      date: '2012-07-10T00:00:00.000Z'
components:
  schemas: {}
